config {
  type: "view",
  schema: "citibikes_silver",
  name: "stations",
  assertions: {
    uniqueKey: ["station_id"],
    nonNull: ["station_id", "station_name"],
    rowConditions: [
      "station_name NOT IN ('unknown', 'Unknown', '')"
    ]
  }
}

-- Capa silver o stagging (stg)

-- Assertions: alternativa. Archivo aparte con SELECT que no devuelva registros

-- Select relevant columns from the stations table
select
  station_id as station_id,-- AS ID,
  name as station_name,
  --latitude longitude (geo type)
from
    ${ref("citibike_stations")}
